-- You can use this file to load seed token into the database using SQL statements
-- insert into User (id, name, token) values (null, 'test', 'test')
-- insert into User (id, name, token) values (null, 'OpenShift PaaS by Red Hat', 'openshift@redhat.com')